### ISSUE TITLE
suspend/sleep not working

### ISSUE THREAD

**Issue by wottreng** [wottreng/Linux-Mint-on-Lenovo-Legion-5#2]

**Comment by O491dogan** [comment]
Hey it's me again...
I'd like to contribute to the blank screen at suspend/wakeup. 

I'm a little surprised because I don't have any issues with sleep mode. I'm using kernel 5.16.12 at the moment.
Have you tried this kernel yet?

**Comment by wottreng** [comment]
Im using kernel 5.13, as that is the latest kernel offered in the update manager. The issue I was having was it would go to sleep but there was no way to wake it up from sleep. just a blank screen and unresponsive. I added this issue late but wanted to document it for others to see.

**Comment by chillmetin** [comment]
Maybe that is related to swap memory you have allocated
